### PR TITLE
Added the possibility to query against custom browser usage data

### PR DESCRIPTION
**Pull request by DanReyLop**
See issue #4.

**New query:**
`> X% in my stats`

**Usage:**
``` js
browserslist("> 5% in my stats", {ga: "path/to/usage_file.json"})
```
Also you can provide the usage info directly, like this:
``` js
var usage = {"ie": {"7":0, "8":4.5, ...}, "chrome": {"34":23.7, ...}, ...}
browserslist("> 5% in my stats", {stats: usage})
```
The expected file format is the same as `require('caniuse-db/region-usage-json/' + country).data`

The code used to parse the data directly from Google Analytics is over 1000 lines long and entangled with other parts of the caniuse.com JS code, so I just implemented a silly workaround:
* Go to http://caniuse.com and import your custom Google Analytics data, as you would normally.
* Paste this snippet into the navigation bar (tested in Chrome):
```js
javascript:(function(){var e=document.createElement('a');e.setAttribute('href', 'data:text/plain;charset=utf-8,'+encodeURIComponent(JSON.stringify(JSON.parse(localStorage['usage-data-by-id'])[localStorage['config-primary_usage']])));e.setAttribute('download','ga.json');document.body.appendChild(e);e.click();document.body.removeChild(e);})()
```

That will give you the JSON file needed by browserslist.

Tell me if the functionality is OK and I'll write some tests for it and update the documentation. Maybe we should adapt the CLI script to support this functionality, or the use of an environment variable to specify the usage file.

### CODE REVIEW

**Comment by ai** [comment]
Great work. I will accept it when I come back to home

**Comment by DanReyLop** [comment]
Please don't accept it as-is. I need to add some tests and also I didn't even check if the current tests pass (seems like they don't, for some reason). Now that I know that you are on board with this patch, I will finish it and document it as soon as I have time (tomorrow).

**Comment by ai** [comment]
Yeap. We need tests and docs changes. Can I ask you to do it, because I am bad in English writing.

I can help you with tests, if you have any questions. You can take some example stats from some small site.

**Comment by DanReyLop** [comment]
Done :)

**Comment by ai** [comment]
Amazing work.

**Comment by DanReyLop** [comment]
Well, that was fast :)
Thanks for the publicity on Twitter :D
Loving the npm ecosystem so far, the tools are so small that anyone can hack into them in no time.

**Pull request merged**
