### PR TITLE
Allow passing stats and env when `—-config` is given (#111)

### PR DESCRIPTION
**Pull request by jrencz**

### CODE REVIEW

**Comment by ai** [comment]
Thanks. I forgot about CLI.

**Comment by ai** [comment]
I will release it tomorrow or aftertomorrow

**Comment by jrencz** [comment]
How do you feel about using more declarative tool for parsing arguments, let's say yargs? I may reorganise CLI with that

**Comment by ai** [comment]
@jrencz CLI tool for Browserslist are not really popular. So making extra dependency for rare feature is not good way :D.

**Pull request merged**
