### PR TITLE
Support resolving shared config from external package

### PR DESCRIPTION
**Pull request by YellowKirby**
Adds support for a special "use" query which requires the corresponding package name and merges that config into the browserslist array.

I didn't add support for automatic `browserslist-config-` prefixing because that gets a little scary with scoped packages. Would be happy to add that in if you think it's necessary.

Related: #122

### CODE REVIEW

**Comment by ai** [comment]
Good idea. Few questions:

1. Should we use `extends` instead of `use` keyword?
2. I think we should fall on wrong path instead of warn and ignore. Users miss warnings.
3. You should put new query code into others queries array.

**Comment by YellowKirby** [comment]
> Should we use extends instead of use keyword?

Yeah, I think that is clearer and more consistent with how eslint, stylelint, etc. are configured.

> I think we should fall on wrong path instead of warn and ignore. Users miss warnings.

Makes sense. Updated.

> You should put new query code into others queries array.

Could you please clarify? I'm not entirely sure what new query code is. I added/updated some tests that use ranges/relative versions (`last 2 versions`) instead of everything referencing an explicit single version (`ie 11`). Is this what you're referring to?

Also any advice on getting the appveyor status to pass? It's timing out on Node 8 but I don't really understand what's failing.

Thanks!

**Comment by ai** [comment]
Great!

Don't worry about AppVeyor, it is on me.

You implement new query by:

```js
queries = flatMap(queries, resolveExternalPackage)
```

But Browserslist implements all other queries by special array of regexps and callbacks:
https://github.com/ai/browserslist/blob/master/index.js#L484

If you will implement `extends` in this `QUERIES` array you will be able to remove some helper functions.

**Comment by YellowKirby** [comment]
Got it, thanks @ai. Should be better now (I needed to move the thing that iterates over `QUERIES` into its own function so that I could call it recursively on the imported arrays). Let me know if there's anything else you'd like me to do.

**Comment by ai** [comment]
There is last concern — security. What is somebody will accept Browserslist query from user and run it from user?

I agree that it is the rare case, but security is important.

What do you think?

My idea (it is only draft, I am open for any suggestions):

1. Extend path must start from `browserslist-config-*`.
2. Extend path should not contain `/../`.
3. Extend path should not contain `/node_modules/`.

This rules will reduce flexibility, but should increase security. Also, we can add `dangerousExtend` option to disable this rules.

**Comment by YellowKirby** [comment]
Would it be easier to just have an optional to disable `extends` queries altogether? If a Browserslist config is being generated from user input then I would imagine the server wouldn't want to trust _any_ dynamic `require` statement.  Given how easy it is for anybody to publish an npm package under any name, I think having a whitelist for certain paths or package names would be fairly simple to circumvent.

Alternatively, could we use something like https://github.com/patriksimek/vm2 (even as just an `optionalDependency`) to sandbox anything that gets `require`d?

**Comment by ai** [comment]
@YellowKirby I thought about disable option too. But the main problem is that users don’t read docs. So without explicit error nobody will think about security.

If we will block query, this error message will force users to read docs and found `dangerousExtend` option.

If we will have `disableExtends` options, nobody will find it, since nobody cares about security before hacker attack :(.

**Comment by ai** [comment]
> Given how easy it is for anybody to publish an npm package under any name, I think having a whitelist for certain paths or package names would be fairly simple to circumvent.

But you need to install npm package first. So users can’t pass `extend browserslist-config-my-hack-npm-package` to server since server’s `package.json` has no `browserslist-config-my-hack-npm-package` in dependencies.

**Comment by ai** [comment]
@YellowKirby if you want I can finish security check. Anyway, you did most of the work, it was really great.

**Comment by YellowKirby** [comment]
@ai sorry I've been busy with some other projects and haven't had much time for this PR. If you want to take the security check stuff that'd be fine. Thanks!

**Comment by ai** [comment]
:+1: I will finish and release it on weekend. Do you have Twitter to mentioned you in announce?

**Comment by YellowKirby** [comment]
Awesome, thank you! I don't have a twitter account or much of an online presence =/

**Comment by YellowKirby** [comment]
@ai: @brianchung808 added in the security stuff talked about in https://github.com/ai/browserslist/pull/171#issuecomment-327378141. Please let us know if there's anything else you'd like us to add/update.

Thanks!

**Comment by ai** [comment]
Awesome! I will try to release it tomorrow on in the weekend. You did a really great work!

**Comment by ai** [comment]
Released in 2.5

**Pull request merged**
