### PR TITLE
Add support for version ranges. Fixes #26.

### LINKED ISSUE #26: Specify a browser version range?
For example:

```js
var legacyIE = browserslist('ie 5.5 through 8');
//=> ['ie 5.5', 'ie 6', 'ie 7', 'ie 8']
```

### PR DESCRIPTION
**Pull request by ben-eb**

### CODE REVIEW

**Comment by ai** [comment]
Maybe `ie 7-9` syntax is more better, especially for non-English speakers? :)

**Comment by ben-eb** [comment]
OK. :smile:

**Comment by ai** [comment]
Can you make a second commit

**Comment by ben-eb** [comment]
Yup, I'll rebase the branch too. :+1:

**Comment by ben-eb** [comment]
Done. :smile:

**Pull request merged**
