### PR TITLE
Add month and date support to since queries

### PR DESCRIPTION
**Pull request by blicksky**
This pull requests adds support for optionally specifying the month and date for since queries. It also fixes an issue where date comparisons were not using UTC timestamps, so release dates that fell on the first of the year (or the first of the month) weren't properly included.

### CODE REVIEW

**Comment by ai** [comment]
Thanks! I will accept and release it after few hours.

**Comment by ai** [comment]
Don’t worry I will fix Travis CI.

**Comment by ai** [comment]
Released in 2.8

**Comment by blicksky** [comment]
Awesome, thanks for merging this so quickly!

**Pull request merged**
