### PR TITLE
Added: `Samsung Internet` and `UC Browser for Android`.

### PR DESCRIPTION
**Pull request by evilebottnawi**
Close https://github.com/ai/browserslist/issues/68. Also add `UC Browser for Android`.

### CODE REVIEW

**Comment by ai** [comment]
Why you want to add so long alias like `SamsungInternet` instead of short `samsung`?

**Comment by ai** [comment]
Also I already updated `README.md` code example :)

**Comment by evilebottnawi** [comment]
@ai offical name is `SamsungInternet`

**Comment by ai** [comment]
@evilebottnawi we use official Can I Use names and shorter aliases :). `Chrome` instead of `GoogleChrome` ;)

**Comment by evilebottnawi** [comment]
@ai ok, let change on `samsung`

> Also I already updated README.md code example :)
Should i remove something from PR?

**Comment by ai** [comment]
> Should i remove something from PR?

sure

**Comment by ai** [comment]
You still mention `SamsungInternet` and you could remove UC Browser Android long name too - it too long.

(I am open if you suggest some better alias for UC)

**Comment by ai** [comment]
Do we have non-Android UC?

**Comment by evilebottnawi** [comment]
@ai at the moment no, but I've heard that ported to `iphone`, `ipad` and etc.

**Comment by ai** [comment]
UCAndroid?

**Comment by evilebottnawi** [comment]
@ai sgtm

**Comment by ai** [comment]
Released in 1.3.6

**Comment by dotnetCarpenter** [comment]
@ai and @evilebottnawi something bad happen. This is completely broken anywhere I test. http://browserl.ist/?q=ucandroid http://browserl.ist/?q=Samsung

I added an issue to [browserl.ist](https://github.com/jonrohan/browserl.ist/issues/87)

**Comment by dotnetCarpenter** [comment]
I've found this because it doesn't work with postcss-next / nuxt / caniuse-api

**Comment by ai** [comment]
@dotnetCarpenter You can’t select browser *version* just by name ;). Use `Samsung > 0`

**Comment by ai** [comment]
Maybe I should create a better error message for this type of mistakes (you are not the first).

**Comment by dotnetCarpenter** [comment]
*Names are case insensitive:*

to be:

*Names are case insensitive and requires a version range (e.g. `> 0`):*

**Comment by ai** [comment]
@dotnetCarpenter or change error text. Like `Version range is missed`

**Comment by dotnetCarpenter** [comment]
And please add the offending name(s)

**Comment by dotnetCarpenter** [comment]
`Version range is missing for Samsung`

`Version range is missing for Samsung, IE`

**Comment by ai** [comment]
Will do it in the end of the week.

**Comment by ai** [comment]
@dotnetCarpenter done 931fb08

**Comment by ai** [comment]
@dotnetCarpenter released in 3.1.2

**Pull request merged**
