### PR TITLE
Resolve `Path must be a string` error

### LINKED ISSUE #158: 2.2.1 breaks stylelint
Sorry, for creating an issue in this manner. I have no time to investigate right now. I'm not sure if it's browserslist's issue, or stylelint's. But we just received two issues about browserlist error, and new browserlist version just released.

https://github.com/stylelint/stylelint/issues/2775
https://github.com/stylelint/stylelint/issues/2774

### PR DESCRIPTION
**Pull request by pieterbeulque**
Fixes #158 

Included a quick & dirty test that fails in 2.2.1 but works with this change.

### CODE REVIEW

**Comment by pieterbeulque** [comment]
Duplicate of #159, apparently, but with an extra test.

**Comment by XhmikosR** [comment]
Cool, closing my PR since this seems to a better solution and with a test 👍

**Comment by sudo-suhas** [comment]
Ha ha.. 3 PRs for one fix. But this is the only one which will pass CI tests 😄 I am closing mine too

**Comment by XhmikosR** [comment]
Mine passed too :P https://travis-ci.org/ai/browserslist/builds/256364450?utm_source=github_status&utm_medium=notification

**Comment by pieterbeulque** [comment]
I can run `stylelint` and `autoprefixer` when linking this patched version from my filesystem instead of using the npm 2.2.1 version.

**Comment by pvdyck** [comment]
Any chance of having 2.2.2 today ? Ionic 2 build process is quite broken and waiting for this. Thanks !

**Comment by mhartington** [comment]
I've reached out to the maintainer. Tested this out locally for ionic-app-scripts and it address the issue.

**Comment by ai** [comment]
Thanks for PR. Sorry, I just wake up :).

**Comment by ai** [comment]
Released in 2.2.2.

**Pull request merged**
