### PR TITLE
Correct documentation typo

### PR DESCRIPTION
**Pull request by joeybaker**

### CODE REVIEW

**Comment by ai** [comment]
Nope, `browserslist` accepts string, not array

**Comment by joeybaker** [comment]
oh, my mistake. But it `['chrome', 'iOS 7']` is valid, right?

**Comment by ai** [comment]
No. Browserslist works with versions. `'chrome'` doesn’t contain version. `'last 2 chrome version'` is valid.

**Comment by joeybaker** [comment]
argh, I'm an idiot, thanks.

**Pull request closed without merging**
